In [2]:
# (공통) 라이브러리 불러오기 및 사용자 함수 정의
import numpy as np

def np_print(nparr):
    print('''
    type : {}  
    shape : {}  
    dimension : {}  
    dtype : {}
    data :\n {}
    '''.format(type(nparr), nparr.shape, nparr.ndim, nparr.dtype, nparr))

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 정렬된 새로운 배열을 반환함
    
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬

In [3]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [0 1 2 3 4]
    


In [4]:
# 기존 파이썬 문법으로 순번 뒤집기
x[::-1]

array([4, 3, 2, 1, 0])

In [5]:
# 오름차순 정렬 테스트용 난수배열 만들기
# 0이상 9이하 숫자 5개를 난수생성으로 만들어서 찍어주세요
a = np.random.randint(0, 10, 5)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [1 4 0 4 0]
    


In [6]:
# np.sort(자료) -> 원본 자료가 바뀌지는 않음
np.sort(a)

array([0, 0, 1, 4, 4])

In [7]:
# 자료.sort() -> 원본자료 변경
a.sort()

In [8]:
a

array([0, 0, 1, 4, 4])

In [9]:
b = np.random.randint(0, 10, 5)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (5,)  
    dimension : 1  
    dtype : int32
    data :
 [1 9 3 3 1]
    


In [10]:
# np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해서는
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌
np.argsort(b)

array([0, 4, 2, 3, 1], dtype=int64)

In [11]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
# np.random.random을 이용하세요
a = np.random.random((3,3))
b = np.random.random(9).reshape(3,3)
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.05373056 0.27817249 0.35846164]
 [0.46635919 0.66616145 0.62260623]
 [0.46403931 0.86249006 0.51986889]]
    

    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.65200046 0.87130261 0.48117242]
 [0.43816425 0.60042225 0.21371364]
 [0.24369523 0.4012674  0.2542431 ]]
    


#### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1 <br>
마지막 axis = 1 (열별 정렬)

<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [12]:
# 기본 방향 (axis=-1) => 열별 정렬
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.05373056 0.27817249 0.35846164]
 [0.46635919 0.66616145 0.62260623]
 [0.46403931 0.86249006 0.51986889]]
    


array([[0.05373056, 0.27817249, 0.35846164],
       [0.46635919, 0.62260623, 0.66616145],
       [0.46403931, 0.51986889, 0.86249006]])

##### axis = 0(열별정렬)

<img src='img/sortaxis0.jpg' width='200' height='200' align='left'>

In [13]:
# 열별 정렬을 시켜보세요.
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>  
    shape : (3, 3)  
    dimension : 2  
    dtype : float64
    data :
 [[0.05373056 0.27817249 0.35846164]
 [0.46635919 0.66616145 0.62260623]
 [0.46403931 0.86249006 0.51986889]]
    


array([[0.05373056, 0.27817249, 0.35846164],
       [0.46403931, 0.66616145, 0.51986889],
       [0.46635919, 0.86249006, 0.62260623]])

## 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱 : 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가 다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개

- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [14]:
# 0 ~ 23 구간으로 1씩 증가하는 값을 아이템으로 가지는 1차원 배열을 생성해주세요
arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [15]:
# 1차원 배열 인덱싱 : 1차원 인덱스 요소 접근
arr1[1]

1

In [16]:
# 1차원 배열 인덱싱 : 마지막 요소 접근
arr1[-1]

23

In [17]:
# 1차원 배열 인덱싱을 통한 값 수정
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [18]:
# 배열 arr1을 이용해 4 * 6 형태의 2차원 배열 arr2 만들기
arr2 = arr1.reshape(4, 6)
np_print(arr2)


    type : <class 'numpy.ndarray'>  
    shape : (4, 6)  
    dimension : 2  
    dtype : int32
    data :
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
    


In [19]:
# 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]
# 하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [20]:
# 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접근
# 반환값 : 1d array
arr2[:, 0]

array([ 0,  6, 12, 18])

In [21]:
# 하나의 값에 접근
# 3행 3열(0번째부터 세서 3행)
arr2[2,2] # arr2[2][2]

14

In [22]:
# 여러개의 행 조회(2차원배열로 조회)
print(arr2)
print('----------------------------')
print(arr2[[0, 3]])

[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]
----------------------------
[[  0   1   2   3   4   5]
 [ 18  19  20  21  22 100]]


In [23]:
# 여러 개의 열 조회
print(arr2[:,[0,2]])
print('----------------------------')
print(arr2)

[[ 0  2]
 [ 6  8]
 [12 14]
 [18 20]]
----------------------------
[[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]


In [24]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하려는 값을 스칼라값으로 전달
# 서로 다른 값으로 수정 : 배열 요소 개수에 맞춰서 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [25]:
# 단일 값이 아닌 여러 값을 대입하고 싶다면
arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [26]:
# 3차원 배열 생성
# 구조 : 2개의 층(면), 4행 3열
# np.arange() => 0 ~ 23까지 24개를 집어넣고 3차원으로 재조정해보세요.
arr3 = np.arange(24).reshape((2, 4, 3))
np_print(arr3)


    type : <class 'numpy.ndarray'>  
    shape : (2, 4, 3)  
    dimension : 3  
    dtype : int32
    data :
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
    


In [27]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
# 0번째 면, 첫 번째 행에 접근시켜주세요.
arr3[0,1]

array([3, 4, 5])

In [29]:
# 1번째 면, 2번 행, 2번 열에 접근
arr3[1, 2, 2]

20

In [30]:
# 3차원 배열 역시 배열 인덱싱으로 값 수정이 가능합니다.
# 스칼라값을 이용한 변경
# arr3의 2번면(0번째부터 세면 1번째)을 0을로 일괄 수정해주세요.
arr3[1] = 0

In [31]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [32]:
# 하나의 면에 대해 서로 다른 값으로 수정 : 요소의 값을 같은 구조, 개수로 전달
# [1, 1]의 값이 현재 0, 0, 0인데 각각 1, 2, 3으로 바꿔주세요
arr3[1, 1] = [1, 2, 3]
arr3[1, 1]

array([1, 2, 3])

In [33]:
# 한 면을 통쨰로 바꾸고 싶다면 같은 크기의 2차원 배열을 대입해줍니다.
arr3[0] = [[10, 20, 30],
          [40, 50, 60],
          [0, 0, 0],
          [0, 0 ,0]]
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 0,  0,  0],
        [ 1,  2,  3],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [34]:
# 여러개의 인덱싱을 배열로 전달
# (행0, 열0), (행1, 열1), (행2, 열2)
# 3차원 배열일 경우에 : [페이지, [[0, 1, 2], [0, 1 ,2]]]
# arr3[면, 행, 열] -> 만약 여러 단위를 조회할 때는 이중리스트로 입력
# 삼중리스트 입력시 이중리스트 요소를 반복
print(arr3[0])
print('===================')
print(arr3[0,[[0, 1, 2], [0, 2, 3]]])

[[10 20 30]
 [40 50 60]
 [ 0  0  0]
 [ 0  0  0]]
[[[10 20 30]
  [40 50 60]
  [ 0  0  0]]

 [[10 20 30]
  [ 0  0  0]
  [ 0  0  0]]]


In [35]:
# 내부 요소 인덱싱시 일반 리스트를 사용하는 경우
# 줄 단위로 가져오는게 아니라 내부 요소로 하나하나를 단위로 가져옵니다.
arr3[0,[0, 1, 2],[0, 1, 2]]

array([10, 50,  0])

### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_index : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [36]:
# 0부터 23까지 1씩 증가하는 정수값을 가지는 1차원 배열을 변수 a에 저장해서 조회해주세요.
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>  
    shape : (24,)  
    dimension : 1  
    dtype : int32
    data :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    


In [37]:
# 1차원 배열 슬라이싱 : 1번부터 4번까지 접근
a[1:5]

array([1, 2, 3, 4])

In [41]:
# 1번째 인덱스부터 14번째 인덱스까지 2씩 증가시키며 접근
a[1:15:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [42]:
# 2차원 배열(6 * 4)로 a의 형태를 바꿔 변수 b에 저장해주시고 화면에 찍어주세요
b = a.reshape(6, 4)
np_print(b)


    type : <class 'numpy.ndarray'>  
    shape : (6, 4)  
    dimension : 2  
    dtype : int32
    data :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
    


In [43]:
# 2차원 배열 슬라이싱 : 1행부터 4행까지 접근
# 2d_array[행(:열:간격)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
# 1행부터 4행에 대해서 2열부터 3열까지 접근
b[1:5,2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [49]:
# 2차원배열 슬라이싱을 통한 값 수정
# 1행부터 4행에 대해 2열부터 3열까지의 모든 배열에 대해서 수정
s_arr = b[1:5, 2:]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [54]:
# 0번째 행과 마지막 열을 제외한 모든 값을 99로 수정
s_arr[1:, 0] = 99

In [55]:
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [56]:
list1 = [1, 2, 3]
list2 = list1

In [57]:
list2[0] = 10
print(list1, list2)

[10, 2, 3] [10, 2, 3]


In [58]:
# 얕은복사로 인한 원본 배열의 변경
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [60]:
# 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열(컬럼)에 대한 인덱싱
# step1. 전체 행에 대해서 접근
# step2. 여러개의 열 인덱싱 배열 전달
# b의 전체 행 + 1, 3번열을 조회해주세요.
b[:, [1, 3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

### 연습문제

아래 정보는 학생들의 학번, 영어 성적, 국어 성적, 수학 성적 정보 입니다. <br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 국어 성적, 네번째 행에 수학 성적을 저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요.

<img src='img/sort_q1.png' align='left'>

In [61]:
data = [[1, 2, 3, 4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]]
arr = np.array(data)

In [79]:
# 영어 성적을 기준으로 오름차순 정렬
np.sort(arr)

array([[ 1,  2,  3,  4],
       [45, 56, 70, 97],
       [33, 67, 84, 87],
       [46, 75, 78, 80]])

In [80]:
arr

array([[ 1,  2,  3,  4],
       [45, 56, 70, 97],
       [87, 84, 33, 67],
       [46, 80, 75, 78]])

In [85]:
# 영어 성적을 기준으로 오름차순 정렬 순위(argsort() 기능 사용하기)
i = np.argsort(arr[1])
i

array([0, 1, 2, 3], dtype=int64)

In [84]:
arr[:, i]

array([[ 1,  2,  3,  4],
       [45, 56, 70, 97],
       [87, 84, 33, 67],
       [46, 80, 75, 78]])